CREATE TABLE `BOARD_CATEGORY` (
	`TYPE`	VARCHAR(20)	NULL,
	`NAME`	VARCHAR(100)	NULL,
	`LEVEL`	INT	NULL,
	`ORDERNO`	INT	NULL
);

CREATE TABLE `MEMBER` (
	`mNO`	INT	NULL,
	`ID`	VARCHAR(30)	NOT NULL,
	`PASSWORD`	VARCHAR(100)	NOT NULL,
	`ROLE`	VARCHAR(10)	NULL	DEFAULT 'ROLE_USER',
	`NAME`	VARCHAR(15)	NOT NULL,
	`PHONE`	VARCHAR(13)	NULL,
	`EMAIL`	VARCHAR(100)	NULL,
	`ADDRESS`	VARCHAR(100)	NULL,
	`HOBBY`	VARCHAR(100)	NULL,
	`KAKAOTOKEN`	VARCHAR(1000)	NULL,
	`NAVERTOKEN`	VARCHAR(1000)	NULL,
	`GOOGLETOKEN`	VARCHAR(1000)	NULL,
	`STATUS`	VARCHAR(1)	NULL,
	`ENROLL_DATE`	DATETIME	NULL,
	`MODIFY_DATE`	DATETIME	NULL
);

CREATE TABLE `BOARD` (
	`bNo`	INT	NOT NULL,
	`mNo`	INT	NULL,
	`TYPE`	VARCHAR(20)	NULL,
	`TITLE`	VARCHAR(1000)	NULL,
	`CONTENT`	VARCHAR(2000)	NULL,
	`ATTACHCOUNT`	INT	NULL,
	`READCOUNT`	INT	NULL,
	`STATUS`	VARCHAR(1)	NULL,
	`CREATE_DATE`	DATETIME	NULL,
	`MODIFY_DATE`	DATETIME	NULL
);

CREATE TABLE `BOARD_ATTACH_FILE` (
	`fNo`	INT	NOT NULL,
	`bNo`	INT	NULL,
	`ORIGINAL_FILENAME`	VARCHAR(200)	NULL,
	`RENAMED_FILENAME`	VARCHAR(200)	NULL,
	`CREATE_DATE`	DATETIME	NULL
);

CREATE TABLE `REPLY` (
	`rNo`	INT	NOT NULL,
	`bNo`	INT	NULL,
	`mNo`	INT	NULL,
	`CONTENT`	VARCHAR(1000)	NULL,
	`STATUS`	VARCHAR(1)	NULL,
	`CREATE_DATE`	DATETIME	NULL,
	`MODIFY_DATE`	DATETIME	NULL
);

CREATE TABLE `TOURIST_ATTRACTION` (
	`CONTENTID`	INT	NOT NULL,
	`CONTENTTYPED`	INT	NULL,
	`HOMEPAGE`	VARCHAR(600)	NULL,
	`TEL`	VARCHAR(100)	NULL,
	`TITLE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE2`	VARCHAR(200)	NULL,
	`AREACODE`	VARCHAR(100)	NULL,
	`SIGUNGUCODE`	VARCHAR(100)	NULL,
	`CAT1`	VARCHAR(100)	NULL,
	`CAT2`	VARCHAR(100)	NULL,
	`CAT3`	VARCHAR(100)	NULL,
	`ADDR1`	VARCHAR(100)	NULL,
	`ADDR2`	VARCHAR(100)	NULL,
	`ZIPCODE`	VARCHAR(100)	NULL,
	`MAPX`	VARCHAR(100)	NULL,
	`MAPY`	VARCHAR(100)	NULL,
	`OVERVIEW`	VARCHAR(500)	NULL,
	`MLEVEL`	VARCHAR(100)	NULL,
	`ACCOMCOUNT`	VARCHAR(100)	NULL,
	`CHKBABYCARRIAGE`	VARCHAR(500)	NULL,
	`CHKCREDITCATRD`	VARCHAR(100)	NULL,
	`CHKPET`	VARCHAR(100)	NULL,
	`EXPAGERANGE`	VARCHAR(100)	NULL,
	`EXPGUIDE`	VARCHAR(100)	NULL,
	`HERITAGE1`	VARCHAR(100)	NULL,
	`HERITAGE2`	VARCHAR(100)	NULL,
	`HERITAGE3`	VARCHAR(100)	NULL,
	`INFOCENTERCULTURE`	VARCHAR(100)	NULL,
	`OPENDATE`	VARCHAR(100)	NULL,
	`PARKING`	VARCHAR(100)	NULL,
	`RESTDATE`	VARCHAR(100)	NULL,
	`USESEASON`	VARCHAR(100)	NULL,
	`USETIME`	VARCHAR(100)	NULL
);

CREATE TABLE `IMAGE` (
	`iNo`	INT	NOT NULL,
	`contentid`	VARCHAR(30)	NULL,
	`imgname`	VARCHAR(30)	NULL,
	`originimgurl`	VARCHAR(150)	NULL,
	`serialnum`	VARCHAR(100)	NULL,
	`cpyrhtDivCd`	VARCHAR(30)	NULL,
	`smallimageurl`	VARCHAR(150)	NULL
);

CREATE TABLE `FESTIVAL` (
	`CONTENTID`	INT	NOT NULL,
	`CONTENTTYPEID`	INT	NOT NULL,
	`HOMEPAGE`	VARCHAR(100)	NULL,
	`TEL`	VARCHAR(100)	NULL,
	`TITLE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE2`	VARCHAR(200)	NULL,
	`AREACODE`	VARCHAR(100)	NULL,
	`SIGUNGUCODE`	VARCHAR(100)	NULL,
	`CAT1`	VARCHAR(100)	NULL,
	`CAT2`	VARCHAR(100)	NULL,
	`CAT3`	VARCHAR(100)	NULL,
	`ADDR1`	VARCHAR(100)	NULL,
	`ADDR2`	VARCHAR(100)	NULL,
	`ZIPCODE`	VARCHAR(100)	NULL,
	`MAPX`	VARCHAR(100)	NULL,
	`MAPY`	VARCHAR(100)	NULL,
	`OVERVIEW`	VARCHAR(100)	NULL,
	`MLEVEL`	VARCHAR(100)	NULL,
	`AGELIMIT`	INT	NULL,
	`BOOKINGPLACE`	VARCHAR(100)	NULL,
	`DISCOUNTINFORFESTIVAL`	VARCHAR(100)	NULL,
	`EVENTENDDATE`	DATE	NULL,
	`EVENTHOMEPAGE`	VARCHAR(100)	NULL,
	`EVENTPLACE`	VARCHAR(100)	NULL,
	`EVENTSTARTDATE`	DATE	NULL,
	`FESTIVALGRADE`	VARCHAR(100)	NULL,
	`PLACEINFO`	VARCHAR(100)	NULL,
	`PLAYTIME`	VARCHAR(100)	NULL,
	`PROGRAM`	VARCHAR(100)	NULL,
	`SPENDTITMEFESTIVAL`	VARCHAR(100)	NULL,
	`SPONSOR1`	VARCHAR(100)	NULL,
	`SPONSOR1TEL`	VARCHAR(100)	NULL,
	`SPONSOR2`	VARCHAR(100)	NULL,
	`SPONSOR2TEL`	VARCHAR(100)	NULL,
	`SUBEVENT`	VARCHAR(100)	NULL,
	`USETIMEFESTIVAL`	INT	NULL
);

CREATE TABLE `FOOD` (
	`CONTENTID`	INT	NULL,
	`CONTENTTYPEID`	INT	NULL,
	`HOMEPAGE`	VARCHAR(600)	NULL,
	`TEL`	VARCHAR(100)	NULL,
	`TITLE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE2`	VARCHAR(200)	NULL,
	`AREACODE`	VARCHAR(100)	NULL,
	`SIGUNGUCODE`	VARCHAR(100)	NULL,
	`CAT1`	VARCHAR(100)	NULL,
	`CAT2`	VARCHAR(100)	NULL,
	`CAT3`	VARCHAR(100)	NULL,
	`ADDR1`	VARCHAR(100)	NULL,
	`ADDR2`	VARCHAR(100)	NULL,
	`ZIPCODE`	VARCHAR(100)	NULL,
	`MAPX`	VARCHAR(100)	NULL,
	`MAPY`	VARCHAR(100)	NULL,
	`OVERVIEW`	VARCHAR(100)	NULL,
	`MLEVEL`	VARCHAR(100)	NULL,
	`CHKCREDITCARDFOOD`	VARCHAR(100)	NULL,
	`DISCOUNTINFOFOOD`	VARCHAR(100)	NULL,
	`FIRSTMENU`	VARCHAR(100)	NULL,
	`INFOCENTERFOOD`	VARCHAR(100)	NULL,
	`KIDSFACILITY`	VARCHAR(100)	NULL,
	`OPENDATEFOOD`	VARCHAR(100)	NULL,
	`OPENTIMEFOOD`	VARCHAR(100)	NULL,
	`PACKING`	VARCHAR(100)	NULL,
	`PARKINGFOOD`	VARCHAR(100)	NULL,
	`RESERVATIONFOOD`	VARCHAR(100)	NULL,
	`RESTDATEFOOD`	VARCHAR(100)	NULL,
	`SCALEFOOD`	VARCHAR(100)	NULL,
	`SEAT`	VARCHAR(100)	NULL,
	`SMOKING`	VARCHAR(100)	NULL,
	`TREATMENU`	VARCHAR(100)	NULL,
	`LCNSNO`	VARCHAR(100)	NULL
);

CREATE TABLE `CULTURECONTENT` (
	`CONTENTID`	INT	NOT NULL,
	`CONTENTTYPEID`	INT	NOT NULL,
	`HOMEPAGE`	VARCHAR(600)	NULL,
	`TEL`	VARCHAR(100)	NULL,
	`TITLE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE`	VARCHAR(200)	NULL,
	`FIRSTIMAGE2`	VARCHAR(200)	NULL,
	`AREACODE`	VARCHAR(100)	NULL,
	`SIGUNGUCODE`	VARCHAR(100)	NULL,
	`CAT1`	VARCHAR(100)	NULL,
	`CAT2`	VARCHAR(100)	NULL,
	`CAT3`	VARCHAR(100)	NULL,
	`ADDR1`	VARCHAR(100)	NULL,
	`ADDR2`	VARCHAR(100)	NULL,
	`ZIPCODE`	VARCHAR(100)	NULL,
	`MAPX`	VARCHAR(100)	NULL,
	`MAPY`	VARCHAR(100)	NULL,
	`OVERVIEW`	VARCHAR(100)	NULL,
	`MLEVEL`	VARCHAR(100)	NULL,
	`ACCOMCOUNTCULTURE`	VARCHAR(100)	NULL,
	`CHKBABYCARRIAGECULTURE`	VARCHAR(100)	NULL,
	`CHKCREDITCARDCULTURE`	VARCHAR(100)	NULL,
	`CHKPETCULTURE`	VARCHAR(100)	NULL,
	`DISCOUNTINFO`	VARCHAR(100)	NULL,
	`INFOCENTERCULTURE`	VARCHAR(100)	NULL,
	`PARKINGCULTURE`	VARCHAR(100)	NULL,
	`PARKINGFEE`	VARCHAR(100)	NULL,
	`RESTDATECULTURE`	VARCHAR(100)	NULL,
	`USEFEE`	VARCHAR(100)	NULL,
	`USETIMECULTURE`	VARCHAR(100)	NULL,
	`SCALE`	VARCHAR(100)	NULL,
	`SPENDTIME`	VARCHAR(100)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`mNO`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`bNo`,
	`mNo`
);

ALTER TABLE `BOARD_ATTACH_FILE` ADD CONSTRAINT `PK_BOARD_ATTACH_FILE` PRIMARY KEY (
	`fNo`
);

ALTER TABLE `REPLY` ADD CONSTRAINT `PK_REPLY` PRIMARY KEY (
	`rNo`,
	`bNo`,
	`mNo`
);

ALTER TABLE `TOURIST_ATTRACTION` ADD CONSTRAINT `PK_TOURIST_ATTRACTION` PRIMARY KEY (
	`CONTENTID`,
	`CONTENTTYPED`
);

ALTER TABLE `IMAGE` ADD CONSTRAINT `PK_IMAGE` PRIMARY KEY (
	`iNo`
);

ALTER TABLE `FESTIVAL` ADD CONSTRAINT `PK_FESTIVAL` PRIMARY KEY (
	`CONTENTID`,
	`CONTENTTYPEID`
);

ALTER TABLE `FOOD` ADD CONSTRAINT `PK_FOOD` PRIMARY KEY (
	`CONTENTID`,
	`CONTENTTYPEID`
);

ALTER TABLE `CULTURECONTENT` ADD CONSTRAINT `PK_CULTURECONTENT` PRIMARY KEY (
	`CONTENTID`,
	`CONTENTTYPEID`
);

